matrix:
  fast_finish: true
  include:
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      language: cpp
      sudo: false
      dist: bionic

    - os: linux
      arch: arm64
      compiler: gcc
      language: cpp
      sudo: false
      dist: bionic

script:
  - gcc -O2 neon.c -o neon
  - objdump -sdtwx neon
  - time ./neon 0 3
  - time ./neon 0 3
  - time ./neon 1 3
  - time ./neon 1 3
  - time ./neon 4 3
  - time ./neon 4 3
  - time ./neon 8 3
  - time ./neon 8 3
  - time ./neon 0 3
  - time ./neon 0 3
  - gcc -O2 regular.c -o regular
  - objdump -sdtwx regular
  - time ./regular 0 3
  - time ./regular 0 3
  - time ./regular 1 3
  - time ./regular 1 3
  - time ./regular 4 3
  - time ./regular 4 3
  - time ./regular 0 3
  - time ./regular 0 3
